name: Run Hotdeal Scraper Every Hour

on:
  schedule:
    # 매시간 정각에 실행 (UTC 기준, 한국 시간 매시 정각과 동일 간격)
    - cron: '0 * * * *'
  # 수동으로 버튼을 눌러 실행할 수 있도록 허용
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run Scraper Script
        run: python scraper.py
